#! /bin/sh

npm install socket.io@0.5.3
npm install oauth@0.8.2
npm install node-static@latest
npm install nstore@latest
npm install http-proxy@latest
npm install less@latest
git submodule init
git submodule update
